CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."FARMERS" 
   (	"FARMER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"DISTRICT" VARCHAR2(50) NOT NULL ENABLE, 
	"SECTOR" VARCHAR2(50) NOT NULL ENABLE, 
	"REGISTRATION_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("FARMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER,  
	"FIRST_NAME" VARCHAR2(50),  
	"LAST_NAME" VARCHAR2(50),   
	"POSITION" VARCHAR2(50),   
	"PHONE" VARCHAR2(15),        
	"SALARY" NUMBER,
	 PRIMARY KEY ("EMPLOYEE_ID")
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."BUYERS" 
   (	"BUYER_ID" NUMBER, 
	"BUYER_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("BUYER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("CATEGORY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE" 
   (	"PRODUCE_ID" NUMBER, 
	"PRODUCE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"UNIT" VARCHAR2(20) NOT NULL ENABLE, 
	"PRICE_PER_KG" NUMBER(10,2) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PRODUCE_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE_CATEGORIES" ("CATEGORY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE_COLLECTIONS" 
   (	"COLLECTION_ID" NUMBER, 
	"FARMER_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCE_ID" NUMBER NOT NULL ENABLE, 
	"EMPLOYEE_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER(10,2) NOT NULL ENABLE, 
	"GRADE" VARCHAR2(20), 
	"COLLECTION_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("COLLECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_COLLECTION_FARMER" FOREIGN KEY ("FARMER_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."FARMERS" ("FARMER_ID") ENABLE, 
	 CONSTRAINT "FK_COLLECTION_PRODUCE" FOREIGN KEY ("PRODUCE_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE" ("PRODUCE_ID") ENABLE, 
	 CONSTRAINT "FK_COLLECTION_EMPLOYEE" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."INVENTORY" 
   (	"INVENTORY_ID" NUMBER, 
	"PRODUCE_ID" NUMBER NOT NULL ENABLE, 
	"AVAILABLE_QUANTITY" NUMBER(10,2) NOT NULL ENABLE, 
	"LAST_UPDATED" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_INVENTORY_PRODUCE" FOREIGN KEY ("PRODUCE_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."PRODUCE" ("PRODUCE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"BUYER_ID" NUMBER NOT NULL ENABLE, 
	"EMPLOYEE_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING', 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ORDER_BUYER" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."BUYERS" ("BUYER_ID") ENABLE, 
	 CONSTRAINT "FK_ORDER_EMPLOYEE" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
CREATE TABLE order_details (
    order_detail_id NUMBER PRIMARY KEY,
    order_id NUMBER NOT NULL,
    produce_id NUMBER NOT NULL,
    quantity NUMBER(10,2) NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_od_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_od_produce FOREIGN KEY (produce_id) REFERENCES produce(produce_id)
);
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."PAYMENTS" 
   (	"PAYMENT_ID" NUMBER, 
	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	"PAYMENT_METHOD" VARCHAR2(30) NOT NULL ENABLE, 
	 PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PAYMENT_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "NTWALIPACCY360_SCHEMA_Y6DM6"."ORDERS" ("ORDER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."PUBLIC_HOLIDAYS" 
   (	"HOLIDAY_ID" NUMBER, 
	"HOLIDAY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"HOLIDAY_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("HOLIDAY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("HOLIDAY_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
CREATE TABLE "NTWALIPACCY360_SCHEMA_Y6DM6"."AUDIT_LOG" 
   (	"AUDIT_ID" NUMBER, 
	"USERNAME" VARCHAR2(50), 
	"ACTION_TYPE" VARCHAR2(20), 
	"TABLE_NAME" VARCHAR2(50), 
	"ACTION_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(200), 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
